In [1]:
import torch
randint = torch.randint(-100,100,(6,))
randint

tensor([-29,  77,  99, -75,  31,  -1])

In [2]:
tensor = torch.tensor([0.1,1.2,23,345,])
tensor


tensor([1.0000e-01, 1.2000e+00, 2.3000e+01, 3.4500e+02])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(23,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linespace = torch.linspace(3,10,steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=10,end=10,steps=6)
logspace

tensor([1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10])

In [11]:
eye = torch.eye(5)#give identity matrix
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty((2,3),dtype=torch.int64)
emptylike = torch.empty_like(a)
emptylike

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:

print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)


False
True
